/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminaldatabase;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FilenameFilter;
import java.nio.IntBuffer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Clock;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bytedeco.javacpp.opencv_core;
import static org.bytedeco.javacpp.opencv_core.CV_32SC1;
import org.bytedeco.javacpp.opencv_face;
import static org.bytedeco.javacpp.opencv_imgcodecs.imread;
import static org.bytedeco.javacpp.opencv_imgcodecs.imwrite;
import org.bytedeco.javacpp.opencv_imgproc;
import static org.bytedeco.javacpp.opencv_imgproc.COLOR_BGRA2GRAY;
import static org.bytedeco.javacpp.opencv_imgproc.cvtColor;
import org.bytedeco.javacpp.opencv_objdetect;

public class CriminalDataUpdate extends javax.swing.JFrame {

    /**
     * Creates new form InsertCriminalData
     */
    public CriminalDataUpdate() {
        this.imgpath = null;
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(Bmale);
        group.add(Bfemale);
        boolean s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        HomeTab = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label16 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        Ffirstname = new java.awt.TextField();
        FCriminalId = new java.awt.TextField();
        Fmiddlename = new java.awt.TextField();
        FLastname = new java.awt.TextField();
        Fdob = new java.awt.TextField();
        Fcity = new java.awt.TextField();
        Fage = new java.awt.TextField();
        Fstate = new java.awt.TextField();
        Ddoarrest = new java.awt.TextField();
        Fcrimeinvolve = new java.awt.TextField();
        Feyeid = new java.awt.TextField();
        Feyename = new java.awt.TextField();
        Fcomplaintid = new java.awt.TextField();
        Acriminaladdress = new java.awt.TextArea();
        Feyeaddress = new java.awt.TextArea();
        FormSubmittion = new java.awt.Button();
        ResetForm = new java.awt.Button();
        Bmale = new javax.swing.JRadioButton();
        Bfemale = new javax.swing.JRadioButton();
        upload_image = new javax.swing.JLabel();
        ChangePic = new javax.swing.JButton();
        AqcureData = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(23, 23));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setAutoscrolls(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criminalimagesResource/Logo_CriminalInvestigation.jpg"))); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Enter Criminal Id");

        HomeTab.setBackground(new java.awt.Color(0, 102, 102));
        HomeTab.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        HomeTab.setForeground(new java.awt.Color(204, 255, 255));
        HomeTab.setLabel("Home");
        HomeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeTabActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("First Name");

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Middle Name");

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Last Name");

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Gender");

        label16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label16.setText("City");

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText("Criminal Address");

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Age");

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("Date of Birth");

        label9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label9.setText("State");

        label13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label13.setText("Complaint Id");

        label14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label14.setText("EveWitness Address");

        label15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label15.setText("EyeWitness Id");

        label10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label10.setText("Crime Involved in");

        label11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label11.setText("Date of arrest");

        label12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label12.setText("EyeWItness Name");

        FCriminalId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FCriminalId.setName(""); // NOI18N
        FCriminalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCriminalIdActionPerformed(evt);
            }
        });

        FormSubmittion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        FormSubmittion.setLabel("Submit");
        FormSubmittion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormSubmittionActionPerformed(evt);
            }
        });

        ResetForm.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ResetForm.setLabel("Reset");
        ResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetFormActionPerformed(evt);
            }
        });

        Bmale.setText("Male");

        Bfemale.setText("Female");
        Bfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfemaleActionPerformed(evt);
            }
        });

        upload_image.setBackground(new java.awt.Color(255, 255, 255));
        upload_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        upload_image.setOpaque(true);
        upload_image.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                upload_imageMouseWheelMoved(evt);
            }
        });
        upload_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upload_imageMouseClicked(evt);
            }
        });

        ChangePic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChangePic.setText("Change Photo");
        ChangePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePicActionPerformed(evt);
            }
        });

        AqcureData.setText("Ok");
        AqcureData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AqcureDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FormSubmittion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(ResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bmale, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(Bfemale))
                            .addComponent(Feyeaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Acriminaladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ffirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FLastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fmiddlename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fdob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fstate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ddoarrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fcrimeinvolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Feyeid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Feyename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fcomplaintid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FCriminalId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AqcureData))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(HomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upload_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChangePic, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(upload_image, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangePic))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FCriminalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AqcureData))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fmiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bmale)
                            .addComponent(Bfemale))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Acriminaladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Fcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ddoarrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fcrimeinvolve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Feyeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Feyename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Feyeaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fcomplaintid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormSubmittion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeTabActionPerformed
        System.out.println("Returning to Home Page");
        frame.dispose();
    }//GEN-LAST:event_HomeTabActionPerformed

    public String imgpath=null;

    private void FormSubmittionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormSubmittionActionPerformed
        int criminalid = Integer.parseInt(FCriminalId.getText());
        String firstname = Ffirstname.getText();
        String lastname = FLastname.getText();
        String middlename = Fmiddlename.getText();
        String dob = Fdob.getText();
        String gender = Bmale.isSelected() ? "Male" : "Female";
        int age = Integer.parseInt(Fage.getText());
        String city = Fcity.getText();
        String state = Fstate.getText();
        String dateofarrest = Ddoarrest.getText();
        String crimeinvolved = Fcrimeinvolve.getText();
        int eyewitnessid = Integer.parseInt(Feyeid.getText());
        String eyewitnessname = Feyename.getText();
        int complaintno = Integer.parseInt(Fcomplaintid.getText());
        String criminaladdress = Acriminaladdress.getText();
        String eyewitnessaddress = Feyeaddress.getText();
        String criminalImage=imgpath;
        /////////////////////
        opencv_core.Mat src = imread(imgpath);
        opencv_core.Mat imageGray = new opencv_core.Mat();
        cvtColor(src, imageGray, COLOR_BGRA2GRAY);

        //Instantiating the CascadeClassifier 
        String xmlFile = "./Haar_File/haarcascade_frontalface_alt.xml";
        opencv_objdetect.CascadeClassifier classifier = new opencv_objdetect.CascadeClassifier(xmlFile);

        //Detecting the face in the snap 
        opencv_core.RectVector faceDetections = new opencv_core.RectVector();

        classifier.detectMultiScale(src, faceDetections);
        System.out.println(String.format("Detected %s faces",
                faceDetections.size()));
//        Integer res = null;
        if (faceDetections.size() <= 0) {
            int res = JOptionPane.showConfirmDialog(CriminalDataUpdate.this, "No Image Found in uploaded Image,\nWould you like to upload anyway?");
//            if (res == JOptionPane.YES_OPTION) {
//                frame.dispose();
//            }
        }
        opencv_core.Rect rectCrop = null;
        opencv_core.RectVector rect = faceDetections;
        rectCrop = new opencv_core.Rect(rect.get(0).x(), rect.get(0).y(), rect.get(0).width(), rect.get(0).height());
        //Writing the image  
        opencv_core.Mat image_roi = new opencv_core.Mat(imageGray, rectCrop);

        System.out.println("Image Processed");
        System.out.println("generation start");
        int sample = 0;

        while (sample < 1) {
            imwrite("./Haar_Images/" + "person." + criminalid + "." + sample + ".jpg", image_roi);
            System.out.println("File Generated " + (sample+1) + "/1");
            sample++;
        }
        generate();
        System.out.println("generation completion");
        ////////////////////////////////////////
        System.out.println("Starting Writting data to database");
        if (DaoCriminalData.checkData(criminalid)) {
            int i = DaoCriminalData.update(criminalid, firstname, lastname, middlename, dob, gender, age,
                    criminaladdress, city, state, dateofarrest, crimeinvolved, eyewitnessid, eyewitnessname,
                    eyewitnessaddress, complaintno,criminalImage);
            
            
            if (i >= 0) {
                System.out.println("Successfully Written\nReturning to home page");
                JOptionPane.showMessageDialog(CriminalDataUpdate.this, "Data Updated successfully!");
                frame.dispose();
            } else {
                System.out.println("Error : Unable to Add");
                JOptionPane.showMessageDialog(CriminalDataUpdate.this, "Sorry, unable to Update!");
            }
        } else {
            System.out.println("Error: Data on this Criminal id Already existed");
            JOptionPane.showMessageDialog(CriminalDataUpdate.this, "Sorry, Data on this Criminal id did'nt exist ");
        }
    }//GEN-LAST:event_FormSubmittionActionPerformed

    private void ResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetFormActionPerformed
        System.out.println("Resetting.....");
        ResourceImagesClass icr = new ResourceImagesClass();
        Ffirstname.setText("");
        FLastname.setText("");
        Fmiddlename.setText("");
        Fdob.setText("");
        Ffirstname.setText("");
        Fage.setText("");
        Fcity.setText("");
        Fstate.setText("");
        Ddoarrest.setText("");
        Fcrimeinvolve.setText("");
        Feyeid.setText("");
        Feyename.setText("");
        Fcomplaintid.setText("");
        Acriminaladdress.setText("");
        Feyeaddress.setText("");
        upload_image.setIcon(icr.ResizeImage("", null,upload_image.getWidth(),upload_image.getHeight()));
        System.out.println("Resetted Fields");
    }//GEN-LAST:event_ResetFormActionPerformed

    private void BfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfemaleActionPerformed
    }//GEN-LAST:event_BfemaleActionPerformed

    private void FCriminalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCriminalIdActionPerformed
    }//GEN-LAST:event_FCriminalIdActionPerformed

    private void upload_imageMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_upload_imageMouseWheelMoved
    }//GEN-LAST:event_upload_imageMouseWheelMoved

    private void ChangePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePicActionPerformed
        System.out.println(imgpath+"  path");
        snapshot s = new snapshot();
        imgpath = s.imgpath;
        ResourceImagesClass icr = new ResourceImagesClass();
        upload_image.setIcon(icr.ResizeImage(imgpath, null, upload_image.getWidth(), upload_image.getHeight()));

//        ResourceImagesClass icr = new ResourceImagesClass();
//        JFileChooser file = new JFileChooser();
//        file.setCurrentDirectory(new File(System.getProperty("user.home")));
//        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.images","jpg", "png");
//        file.addChoosableFileFilter(filter);
//        int result=file.showSaveDialog(null);
//        if(result==JFileChooser.APPROVE_OPTION){
//            File selectedFile = file.getSelectedFile();
//            String path=selectedFile.getAbsolutePath();
//            upload_image.setIcon(icr.ResizeImage(path, null,upload_image.getWidth(),upload_image.getHeight()));
//            imgpath=path;
//            
//            System.out.println(imgpath);
//        }else{
//            System.out.println("No File Selected");
//        }
        System.out.println("imgpath = "+imgpath);
    }//GEN-LAST:event_ChangePicActionPerformed

    private void AqcureDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AqcureDataActionPerformed
        System.out.println("Geeting Criminal Id And Data Corresspond to that");
        ResourceImagesClass icr = new ResourceImagesClass();
        String sid = FCriminalId.getText();
        if (sid == null || sid.trim().equals("")) {
            System.out.println("Id can't be blank");
            JOptionPane.showMessageDialog(CriminalDataUpdate.this, "Id can't be blank");
        } else {
            int id = Integer.parseInt(sid);
            if (DaoCriminalData.checkData(id)) {
                try {
                    int status = 0;
                    System.out.println("Connecting to Database");
                    Connection con = DB.getConnection();
                    System.out.println("Connected");
                    PreparedStatement ps = con.prepareStatement("select * from CriminalData where criminalid=?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    ps.setInt(1, id);
                    ResultSet rs = ps.executeQuery();
                    rs.beforeFirst();
                    rs.next();
                    Ffirstname.setText(rs.getString(3));
                    FLastname.setText(rs.getString(4));
                    Fmiddlename.setText(rs.getString(5));
                    Fdob.setText(rs.getString(6));
                    Bmale.setSelected(true);
                    if (rs.getString(7).equals("Male") == true) {
                        Bmale.setSelected(true);
                    } else {
                        Bfemale.setSelected(true);
                    }
                    Fage.setText(rs.getString(8));
                    Fcity.setText(rs.getString(10));
                    Fstate.setText(rs.getString(11));
                    Ddoarrest.setText(rs.getString(12));
                    Fcrimeinvolve.setText(rs.getString(13));
                    Feyeid.setText(rs.getString(14));
                    Feyename.setText(rs.getString(15));
                    Fcomplaintid.setText(rs.getString(17));
                    Acriminaladdress.setText(rs.getString(9));
                    Feyeaddress.setText(rs.getString(16));
                  //  byte[] imagebytes = rs.getBytes("image");
                    String CrimName=rs.getInt(2)+rs.getString(3);
                    upload_image.setIcon(icr.ResizeImage(rs.getString(18), null,upload_image.getWidth(),upload_image.getHeight()));
//upload_image.setIcon(ResizeImage("./Images/Criminalimg/" + CrimName + "/" + CrimName + ".png", null));
                    con.close();
                } catch (SQLException ex) {
                    System.out.println("Exception Caught");
                    Logger.getLogger(CriminalDataUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Retrieval Complete");
                JOptionPane.showMessageDialog(CriminalDataUpdate.this, "Update the details and then submit!");
            } else {
                System.out.println("Error: Record Not Found");
                JOptionPane.showMessageDialog(CriminalDataUpdate.this, "Reord not found to update given id!");
            }
        }
    }//GEN-LAST:event_AqcureDataActionPerformed

    private void upload_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upload_imageMouseClicked
        System.out.println("Opening Snapshot Window");
        snapshot.main(new String[]{});
        // TODO add your handling code here:
    }//GEN-LAST:event_upload_imageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriminalDataUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriminalDataUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriminalDataUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriminalDataUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new CriminalDataUpdate();
                frame.setVisible(true);
                frame.setPreferredSize(new Dimension(500, 500));
                frame.setResizable(false);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Acriminaladdress;
    private javax.swing.JButton AqcureData;
    private javax.swing.JRadioButton Bfemale;
    private javax.swing.JRadioButton Bmale;
    private javax.swing.JButton ChangePic;
    private java.awt.TextField Ddoarrest;
    private java.awt.TextField FCriminalId;
    private java.awt.TextField FLastname;
    private java.awt.TextField Fage;
    private java.awt.TextField Fcity;
    private java.awt.TextField Fcomplaintid;
    private java.awt.TextField Fcrimeinvolve;
    private java.awt.TextField Fdob;
    private java.awt.TextArea Feyeaddress;
    private java.awt.TextField Feyeid;
    private java.awt.TextField Feyename;
    private java.awt.TextField Ffirstname;
    private java.awt.TextField Fmiddlename;
    private java.awt.Button FormSubmittion;
    private java.awt.TextField Fstate;
    private java.awt.Button HomeTab;
    private java.awt.Button ResetForm;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel upload_image;
    // End of variables declaration//GEN-END:variables
    static CriminalDataUpdate frame;

    public void generate() {
        System.out.println("Generating Images...");
        File directory = new File("./Haar_Images/");
        FilenameFilter filter = new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.endsWith(".jpg") || name.endsWith(".png");
            }
        };

        File[] files = directory.listFiles(filter); //only our filter
        opencv_core.MatVector photos = new opencv_core.MatVector(files.length);
        opencv_core.Mat labels = new opencv_core.Mat(files.length, 1, CV_32SC1);
        IntBuffer labelsBuffer = labels.createBuffer();

        int counter = 0;
        for (File image : files) {
            opencv_core.Mat photo = imread(image.getAbsolutePath(), COLOR_BGRA2GRAY);
            int idP = Integer.parseInt(image.getName().split("\\.")[1]);
            opencv_imgproc.resize(photo, photo, new opencv_core.Size(160, 160));
            System.out.println(image.getName());
            System.out.println("idp " + idP);
            photos.put(counter, photo);
            labelsBuffer.put(counter, idP);
            counter++;
        }

        opencv_face.FaceRecognizer lbph = opencv_face.LBPHFaceRecognizer.create();
        System.out.println("Trainning LBPH file");
        lbph.train(photos, labels);
        System.out.println("Trainned Successfully");
        lbph.save("./Haar_Images/classifierLBPH.yml");
        System.out.println("LBPH File saved Successfully at ./Haar_Images/classifierLBPH.yml");
    }
}
